<?php echo $this->getContent(); ?>

<ul class="nav nav-tabs" id="pTab">
    <li class="active"><a href="#create" data-toggle="tab">สร้างแบบฟอร์ม</a></li>
    <li><a href="#upload" data-toggle="tab">อัพโหลดคะแนน</a></li>
</ul><br>

<div class="tab-content">
    <!-- Upload Form -->
    <div class="tab-pane fade in" id="upload">
        <form class="form-horizontal" action="<?= $this->url->get('score/uploadScore'); ?>" method="post"
              enctype="multipart/form-data">
            <div class="form-group col-sm-offset-2 col-sm-3">
                <?php

                $this->tag->setDefault('semester_id', $currentSemesterId);

                echo $this->tag->selectStatic(array(

                    'semester_id',
                    $allSemesters,
                    'class' => 'form-control',
                    'required' => 'required'
                ));

                ?>
            </div>
            <div class="form-group col-sm-offset-2 col-sm-10">
                <?= Phalcon\Tag::filefield("scorefile"); ?>
            </div>
            <div class="form-group col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success btn-sm">อัพโหลด</button>
            </div>
        </form>
    </div>

    <!-- Create Form -->
    <div class="tab-pane fade in active" id="create">
        <form class="form-horizontal" action="<?= $this->url->get('score/createScore'); ?>" method="post">
            <div class="form-group col-sm-offset-2 col-sm-3">
                <?php

                $this->tag->setDefault('semester_id', $currentSemesterId);

                echo $this->tag->selectStatic(array(
                    'semester_id',
                    $allSemesters,
                    'class' => 'form-control',
                    'required' => 'required'
                ));

                ?>
            </div>
            <div class="form-group col-sm-offset-2 col-sm-10">
                <input type="checkbox" name="all" id="all" value="all"> ทั้งหมด
            </div>
            <div class="form-group col-sm-offset-2 col-sm-10">
                <?php
                $users = User::find("type='advisor'");

                foreach ($users as $user)
                {
                    ?>
                    <input type="checkbox" name="advisor[]" id="advisor[]"
                           value="<?= $user->id ?>"> <?= $user->title . $user->name ?>
                    <br>
                <?php
                }
                ?>
            </div>
            <div class="form-group col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success btn-sm">สร้างแบบฟอร์ม</button>
            </div>
        </form>
    </div>
</div>
