<?php echo $this->getContent(); ?>
<?php

$auth = $this->session->get('auth');
$user_id = $auth['id'];

$newss = News::find(array("order" => "id DESC", "limit" => 8));

?>

<div class="row">
    <table width="100%">
        <tr>
            <td width="19%">
                <a href="<?= $this->url->get('advisor/advisorList'); ?>" class="btn btn-primary btn-lg btn-block">
                    Advisor<br>Profiles
                </a>
            </td>
            <td width="1%"></td>
            <td width="19%">
                <a href="<?= $this->url->get('projects/newProject'); ?>" class="btn btn-primary btn-lg btn-block">
                    New<br>Project
                </a>
            </td>
            <td width="1%"></td>
            <td width="19%">
                <a href="<?= $this->url->get('projects/me'); ?>" class="btn btn-primary btn-lg btn-block">
                    Manage<br>Project
                </a>
            </td>
            <td width="1%"></td>
            <td width="19%">
                <a href="<?= $this->url->get('exam/showExam'); ?>" class="btn btn-primary btn-lg btn-block">
                    Exam<br>Schedule
                </a>
            </td>
            <td width="1%"></td>
            <td width="19%">
                <a href="<?= $this->url->get('score/studentView'); ?>" class="btn btn-primary btn-lg btn-block">
                    View<br>Score
                </a>
            </td>
        </tr>
    </table>
</div>
<br>
<div class="row">
    <h4>News</h4>

    <div class="panel panel-info">
        <div class="panel-body">
            <ul>
                <?php

                foreach ($newss as $news)
                {
                    ?>
                    <li><?= $news->create_date . ' ' . $news->news; ?></li>
                <?php
                }
                ?>
            </ul>
        </div>
    </div>
</div>
<div class="row">
    <h4>Log</h4>

    <div class="panel panel-info">
        <div class="panel-body">
            <?php
            $logs = Log::find(array("conditions" => "user_id='$user_id'", "order" => "create_date DESC"));
            echo '<ul>';
            foreach ($logs as $log)
            {
                echo '<li>' . $log->create_date . ' ' . $log->description . '</li>';
            }

            echo '</ul>';
            ?>
        </div>
    </div>
</div>
