<?php echo $this->getContent(); ?>
<?php

$auth = $this->session->get('auth');
$user_id = $auth['id'];

$newss = News::find(array("order" => "id DESC", "limit" => 8));

?>
<div class="row">
    <div class="col-sm-3">
        <a href="<?= $this->url->get('advisor/list'); ?>" class="btn btn-primary btn-lg btn-block" name="advisor_list">
            Advisor<br>Profiles
        </a>
    </div>

    <div class="col-sm-3">
        <a href="<?= $this->url->get('projects/newProject'); ?>" class="btn btn-primary btn-lg btn-block">
            New<br>Project
        </a>
    </div>

    <div class="col-sm-3">
        <a href="<?= $this->url->get('projects/me'); ?>" class="btn btn-primary btn-lg btn-block">
            Manage<br>Project
        </a>
    </div>
    <div class="col-sm-3">
        <a href="<?= $this->url->get('exam/showExam'); ?>" class="btn btn-primary btn-lg btn-block">
            Exam<br>Schedule
        </a>
    </div>
</div>
<br>
<div class="row">
    <h4>News</h4>

    <div class="panel panel-info">
        <div class="panel-body">
            <ul>
                <?php

                foreach ($newss as $news)
                {
                    ?>
                    <li><?= $news->create_date . ' ' . $news->news; ?></li>
                    <?php
                }
                ?>
            </ul>
        </div>
    </div>
</div>
<div class="row">
    <h4>Log</h4>

    <div class="panel panel-info">
        <div class="panel-body">
            <?php
            $logs = Log::find(array("conditions" => "user_id='$user_id'", "order" => "create_date DESC", "limit" => 8));
            echo '<ul>';
            foreach ($logs as $log)
            {
                echo '<li>' . $log->create_date . ' ' . $log->description . '</li>';
            }

            echo '</ul>';
            ?>
        </div>
    </div>
</div>
