<?php echo $this->getContent(); ?>



<div class="row">
    <?php require(__DIR__ . '/../layouts/projectHeader.php'); ?>
    <div class="tab-content">
        <div class="tab-pane fade in active" id="progress">
            <br>
            <a href="<?= $this->url->get('progress/newProgress/') . $project->project_id; ?>"
               class="btn btn-xs btn-success pull-right">New Progress</a>
            <br>
            <br>

            <div>
                <table class="table" width="100%">
                    <tr class="success">
                        <th><?= $project->project_name ?> progress ที่ยังไม่ประเมิน</th>
                        <th></th>
                        <th width="20%"></th>
                    </tr>
                    <?php

                    foreach ($nonEvalProgresss as $progress)
                    {
                        $user = User::findFirst(array(
                            "conditions" => "id=:user_id:",
                            "bind" => array("user_id" => $progress->user_id)
                        ));

                        ?>
                        <tr>
                            <td>
                                <?= $user->name ?>
                            </td>
                            <td>
                                <?= $progress->create_date ?>
                            </td>
                            <td>
                                <a href="<?= $this->url->get('progress/view/'); ?><?= $params[0] ?>/<?= $progress->progress_id ?>"
                                   class="btn btn-xs btn-success" target="popup">View</a>
                                <a href="<?= $this->url->get('progress/delete/') . $params[0] . '/' . $progress->progress_id; ?>"
                                   class="btn btn-xs btn-danger"
                                   onclick="return confirm('Confirm Delete');">Delete</a>
                            </td>
                        </tr>
                    <?php
                    }
                    ?>
                </table>
                <table class="table" width="100%">
                    <tr class="success">
                        <th><?= $project->project_name ?> progress ที่ประเมินแล้ว</th>
                        <th></th>
                        <th width="30%"></th>
                        <th width="10%"></th>
                    </tr>

                    <?php
                    foreach ($evaledProgresss as $progress)
                    {
                        $user = User::findFirst(array(
                            "conditions" => "id=:user_id:",
                            "bind" => array("user_id" => $progress->user_id)
                        ));
                        ?>

                        <tr>
                            <td>
                                <?= $user->name ?>
                            </td>
                            <td>
                                <?= $progress->create_date ?>
                            </td>
                            <td>
                                <a href="<?= $this->url->get('progress/view/'); ?><?= $params[0] ?>/<?= $progress->progress_id ?>"
                                   class="btn btn-xs btn-success" target="popup">View</a>
                                <a href="<?= $this->url->get('progress/delete/') . $params[0] . '/' . $progress->progress_id; ?>"
                                   class="btn btn-xs btn-danger"
                                   onclick="return confirm('Confirm Delete');">Delete</a>
                            </td>
                            <td>
                                <?php
                                $evaluate = ProgressEvaluate::findFirst(array(
                                    "conditions" => "progress_id=:progress_id:",
                                    "bind" => array("progress_id" => $progress->progress_id)
                                ));

                                if ($evaluate->evaluation == '1')
                                    echo 'ต้องปรับปรุง';
                                else if ($evaluate->evaluation == '2')
                                    echo 'พอใช้';
                                else
                                    echo 'ดี';
                                ?>
                            </td>
                        </tr>
                    <?php
                    }
                    ?>
                </table>
            </div>
        </div>
    </div>
</div>
</div>
