<?php
echo $this->getContent();
$params = $this->dispatcher->getParams();
?>


<div class="row">
    <?php require(__DIR__ . '/../layouts/projectHeader.php'); ?>
    <div class="tab-content">
        <div class="tab-pane fade in active" id="progress">
            <br>

            <div class="pull-right">
                <a href="<?= $this->url->get('progress/newProgress/'); ?><?= $params[0] ?>"
                   class="btn btn-xs btn-success">New Progress</a>
                <a href="<?= $this->url->get('progress/exportPDF/') . $params[0]; ?>"
                   class="btn btn-xs btn-primary">Export PDF</a>
            </div>
            <br>
            <br>
            <table class="table" width="100%">
                <tr class="success">
                    <th><?= $project->project_name ?> progress</th>
                    <th></th>
                    <th width="15%"></th>
                </tr>
                <?php

                $project = Project::findFirst(array(
                    "conditions" => "project_id=:project_id:",
                    "bind" => array("project_id" => $params[0])
                ));

                $progresss = Progress::find("project_id='$project->project_id'");
                foreach ($progresss as $progress)
                {
                    $user = User::findFirst("id='$progress->user_id'");
                    ?>
                    <tr>
                        <td>
                            <?= $user->name ?>
                        </td>
                        <td>
                            <?= $progress->create_date ?>
                        </td>
                        <td>
                            <a href="<?= $this->url->get('progress/view/'); ?><?= $params[0] ?>/<?= $progress->progress_id ?>"
                               class="btn btn-xs btn-success">View</a>
                            <?php
                            if ($progress->user_id == $auth['id'])
                            {
                                ?>
                                <a href="<?= $this->url->get('progress/delete/'); ?><?= $params[0] ?>/<?= $progress->progress_id ?>"
                                   class="btn btn-xs btn-danger" onclick="return confirm('Confirm Delete');">Delete</a>
                            <?php
                            }
                            ?>
                        </td>
                    </tr>
                <?php
                }
                ?>
            </table>
        </div>
    </div>
</div>
</div>
