<?php

echo $this->getContent();

?>

<div class="row">

    <h4>เพิ่มรายชื่อนักศึกษา</h4>

    <form class="form-horizontal" action="<?= $url.'enroll/doAddUser'; ?>" method="post">
        <div class="form-group">
            <label class="col-sm-2 control-label">วิชา</label>

            <div class="col-sm-5">
                <?php

                echo \Phalcon\Tag::select([
                    'project_level',
                    $projectLevels,
                    'using' => ['project_level_id', 'project_level_name'],
                    'required' => 'required',
                    'class' => 'form-control'
                ]);

                ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">รหัสนักศึกษา</label>

            <div class="col-sm-4">
                <?php

                echo \Phalcon\Tag::textField([
                   'student_id',
                    'class' => 'form-control',
                    'required' => 'required'
                ]);

                ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success btn-sm">เพิ่มรายชื่อ</button>
            </label>
        </div>
    </form>
</div>