<style>
    .table th, .table td {
        border-top: none !important;
    }

    .freeslot {
        background-color: transparent;

    }

    .staffslot {
        background-color: #FFD700;
    }

    .bslot {
        background-color: #739FD0;
    }

    .aslot {
        background-color: #3566A1;
    }

    .cslot {
        background-color: #3399FE;
    }

    .dslot {
        background-color: #82CBFE;
    }

    .eslot {
        background-color: #D0E6F1;
    }
</style>

<div class="table-responsive table-bordered">
    <table class="table table-responsive borderless">
        <?php

        for ($i = 0 ; $i < 11 ; $i++)
        {
            ?>
            <tr>
                <?php
                for ($j = 0 ; $j < 13 ; $j++)
                {
                    $room = Room::findFirst([
                        'conditions' => 'col=:col: AND row=:row:',
                        'bind' => ['row' => $i, 'col' => $j]
                    ]);

                    if ($room->status == 'in_use')
                        $text = '<span class="glyphicon glyphicon-user" style="color: red;"></span>';
                    elseif ($room->status == 'pending')
                        $text = '<span class="glyphicon glyphicon-user" style="color: orange;"></span>';
                    else
                        $text = $room->text;

                    ?>

                    <td>
                        <button class="btn btn-block <?= $room->class; ?>"><?= $text ?></button>
                    </td>

                    <?php
                }
                ?>
            </tr>
            <?php
        }
        ?>
    </table>
</div>

<br>

<h2>หมายเหตุ</h2>
<ul>
    <li>
        Zone A B C ใช้ระบบเครือข่ายผ่านสาย Lan เท่านั้น
    </li>
    <li>
        Zone D E ใช้ระบบเครือข่ายผ่าน CoE-WiFi เท่านั้น
    </li>
    <li>
        <span class="glyphicon glyphicon-user" style="color: red;"></span> คือ มีคนใช้งานแล้ว (ยืนยันแล้ว
        ไม่สามารถย้ายที่ได้)
    </li>
    <li>
        <span class="glyphicon glyphicon-user" style="color: orange;"></span> คือ มีคนใช้งานแล้ว (รอยืนยัน)
    </li>
</ul>
