<?php

$auth = $this->session->get('auth');

?>

<style>
    .table th, .table td {
        border-top: none !important;
    }

    .freeslot {
        background-color: transparent;

    }

    .staffslot {
        background-color: #FFD700;
    }

    .bslot {
        background-color: #739FD0;
    }

    .aslot {
        background-color: #3566A1;
    }

    .cslot {
        background-color: #3399FE;
    }

    .dslot {
        background-color: #82CBFE;
    }

    .eslot {
        background-color: #D0E6F1;
    }

    .success {
        color: green;
    }

    .warning {
        color: orange;
    }

    .error {
        color: red;
    }
</style>

<h3>สภานะปัจจุบัน <span class="<?= $status_type; ?>"><?= $current_status; ?></span></h3>

<div class="table-responsive table-bordered">
    <table class="table table-responsive borderless">
        <?php

        for ($i = 0 ; $i < 11 ; $i++)
        {
            ?>
            <tr>
                <?php
                for ($j = 0 ; $j < 13 ; $j++)
                {
                    $room = Room::findFirst([
                        'conditions' => 'col=:col: AND row=:row:',
                        'bind' => ['row' => $i, 'col' => $j]
                    ]);

                    if ($room->status == 'in_use')
                    {
                        if ($room->user_id == $auth['id'])
                            $text = '<span class="glyphicon glyphicon-user" style="color: yellow;"></span>';
                        else
                            $text = '<span class="glyphicon glyphicon-user error" style="color: red;"></span>';
                    }
                    else if ($room->status == 'pending')
                        $text = '<span class="glyphicon glyphicon-user warning"></span>';
                    else
                        $text = $room->text;

                    ?>

                    <td>
                        <button class="btn btn-block <?= $room->class; ?>"><?= $text ?></button>
                    </td>

                    <?php
                }
                ?>
            </tr>
            <?php
        }
        ?>
    </table>
</div>


<br>

<?php
if ($status == 'can_request'):

    ?>

    <a href="<?= $url . 'room/newRequest'; ?>" class="btn btn-sm btn-primary">คลิกที่นี่เพื่อทำการขอใช้ห้องโครงงาน</a>

    <?php

elseif ($status == 'can_select_seat'):
    ?>

    <a href="<?= $url . 'room/selectSeat'; ?>" class="btn btn-sm btn-primary">คลิกที่นี่เพื่อเลือกที่นั่ง</a>

    <?php
endif;
?>

<h2>หมายเหตุ</h2>
<ul>
    <li>Project I เริ่มจองได้ตั้งแต่วันที่: <?= $p1_start; ?></li>
    <li>Project II เริ่มจองได้ตั้งแต่วันที่: <?= $p2_start; ?></li>
    <li>
        Zone A B C ใช้ระบบเครือข่ายผ่านสาย Lan เท่านั้น
    </li>
    <li>
        Zone D E ใช้ระบบเครือข่ายผ่าน CoE-WiFi เท่านั้น
    </li>
    <li>
        <span class="glyphicon glyphicon-user" style="color: red;"></span> คือ มีคนใช้งานแล้ว (ยืนยันแล้ว
        ไม่สามารถย้ายที่ได้)
    </li>
    <li>
        <span class="glyphicon glyphicon-user" style="color: yellow;"></span> คือ ที่นั่งของนักศึกษา (ยืนยันแล้ว
        ไม่สามารถย้ายที่ได้)
    </li>
</ul>


