<?php

$auth = $this->session->get('auth');

echo \Phalcon\Tag::stylesheetLink('lib/custom/roomseat.css')

?>


<h3>สภานะปัจจุบัน <span class="<?= $status_type; ?>"><?= $current_status; ?></span></h3>

<?php

require __DIR__.'/roomMap.phtml';

?>

<br>

<?php
if ($status == 'can_request'):

    ?>

    <a href="<?= $url . 'room/newRequest'; ?>" class="btn btn-sm btn-primary">คลิกที่นี่เพื่อทำการขอใช้ห้องโครงงาน</a>

    <?php

elseif ($status == 'can_select_seat'):
    ?>

    <a href="<?= $url . 'room/selectSeat'; ?>" class="btn btn-sm btn-primary">คลิกที่นี่เพื่อเลือกที่นั่ง</a>

    <?php
endif;
?>

<h2>หมายเหตุ</h2>
<ul>
    <li>Project I เริ่มจองได้ตั้งแต่วันที่: <?= $p1_start; ?></li>
    <li>Project II เริ่มจองได้ตั้งแต่วันที่: <?= $p2_start; ?></li>
    <li>
        Zone A B C ใช้ระบบเครือข่ายผ่านสาย Lan เท่านั้น
    </li>
    <li>
        Zone D E ใช้ระบบเครือข่ายผ่าน CoE-WiFi เท่านั้น
    </li>
    <li>
        <span class="glyphicon glyphicon-user" style="color: red;"></span> คือ มีคนใช้งานแล้ว (ยืนยันแล้ว
        ไม่สามารถย้ายที่ได้)
    </li>
    <li>
        <span class="glyphicon glyphicon-user" style="color: yellow;"></span> คือ ที่นั่งของนักศึกษา (ยืนยันแล้ว
        ไม่สามารถย้ายที่ได้)
    </li>
</ul>


