<?php

echo $this->getContent(); 

?>

<form class="form-horizontal" role="form" method="post" action="<?= $this->url->get('news/doCreate'); ?>">
	<div class="form-group">
		<label class="col-sm-2 control-label">News</label>
		<div class="col-sm-10">
		<?=
			$this->tag->textField(array(
				'news',
				'class' => 'form-control'
			));
		?>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-success btn-sm">Create</button>
		</div>
	</div>
</form>
