<?php

echo $this->getContent();
$params = $this->dispatcher->getParams();
$id = $params[0];

$news = News::findFirst("id='$id'");

?>

<script type="text/javascript">

    tinymce.init({
        selector: "textarea#news",
        theme: "modern",
        plugins: [
            "advlist autolink lists link image charmap print preview hr anchor pagebreak",
            "searchreplace wordcount visualblocks visualchars code fullscreen",
            "insertdatetime media nonbreaking save table contextmenu directionality",
            "template paste textcolor"
        ],
        toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image print preview media | forecolor backcolor emoticons",
        image_advtab: true,
        autosave_ask_before_unload: false,
        width: "100%",
        height: "200px"
    });
</script>

<form class="form-horizontal" role="form" method="post" action="<?= $this->url->get('news/doEdit'); ?>">
    <input type="hidden" name="id" value="<?= $id; ?>">

    <div class="form-group">
        <label class="col-sm-2 control-label">News</label>

        <div class="col-sm-10">
            <?=
            $this->tag->textArea(array('news', 'value' => $news->news));
            ?>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success btn-sm">Edit</button>
        </div>
    </div>
</form>
