<?php

echo $this->getContent();
$params = $this->dispatcher->getParams();
$id = $params[0];

$news = News::findFirst("id='$id'");

?>

<form class="form-horizontal" role="form" method="post" action="<?= $this->url->get('news/doEdit'); ?>">
    <input type="hidden" name="id" value="<?= $id; ?>">

    <div class="form-group">
        <label class="col-sm-2 control-label">News</label>

        <div class="col-sm-10">
            <?=
            $this->tag->textField(array(
                'news',
                'class' => 'form-control',
                'value' => $news->news
            ));
            ?>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success btn-sm">Edit</button>
        </div>
    </div>
</form>
