<?php

echo $this->getContent();

?>

<h4>เพิ่มปีการศึกษา</h4>
<form class="form-horizontal" method="post" action="<?= $this->url->get('settings/addSemester'); ?>">
    <div class="form-group">
        <label class="col-sm-2 control-label">ภาคเรียที่</label>

        <div class="col-sm-2">
            <?php

            echo $this->tag->selectStatic(array(
                'term',
                array(
                    '1' => '1',
                    '2' => '2',
                    '3' => '3'
                ),
                'class' => 'form-control',
                'required' => 'required'
            ));

            ?>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">ปี</label>

        <div class="col-sm-3">
            <?php

            echo $this->tag->numericField(array('year', 'class' => 'form-control', 'required' => 'required'));

            ?>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary btn-sm">เพิ่ม</button>
            <a href="<?= $this->url->get('settings'); ?>" class="btn btn-warning btn-sm">ยกเลิก</a>
        </div>
    </div>
</form>