<?php echo $this->getContent(); ?>

<script type="text/javascript">

    tinymce.init({
        selector: "textarea#description",
        theme: "modern",
        plugins: [
            "advlist autolink lists link image charmap print preview hr anchor pagebreak",
            "searchreplace wordcount visualblocks visualchars code fullscreen",
            "insertdatetime media nonbreaking save table contextmenu directionality",
            "emoticons template paste textcolor"
        ],
        toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image print preview media | forecolor backcolor emoticons",
        image_advtab: true,
        autosave_ask_before_unload: false,
        width: "100%",
        height: "200px"
    });
</script>


<?php require(__DIR__ . '/../layouts/projectHeader.php'); ?>
<?php
$params = $this->dispatcher->getParams();

?>
<div class="tab-content">
    <div class="tab-pane fade in active" id="setting">
        <br>

        <?php

        if ($selectProject->project_status == "Pending" && $auth['type'] == 'Student'):
            ?>
            <div class="alert alert-info"><a href="<?= $url; ?>projects/delete/<?= $selectProject->project_id; ?>"
                                             class="btn btn-danger btn-xs"
                                             onclick="return confirm('ยินยันการลบโครงงาน');">Cancel Request</a></div>
            <?php

        elseif ($selectProject->project_status == "Pending"):
            ?>
            <div class="alert alert-info">รอยืนยัน</div>
            <?php
        endif;
        ?>
        <form class="form-horizontal" action="<?= $this->url->get('projects/editSetting'); ?>" method="post">
            <input type="hidden" id="id" name="id" value="<?= $selectProject->project_id ?>">

            <div class="form-group">
                <label class="col-sm-2 control-label">Project Name</label>

                <div class="col-sm-8">
                    <?php

                    \Phalcon\Tag::setDefault('name', $selectProject->project_name);

                    echo \Phalcon\Tag::textField(array(
                        'name',
                        'class' => 'form-control',
                        'required' => 'required',
                        'placeholder' => 'Project Name',
                        'maxlength' => '50'
                    ));

                    ?>
                    <p class="help-block">ใส่เฉพาะชื่อภาษาไทย <strong>หรือ</strong> ภาษาอังกฤษ จำกัดความยาวไม่เกิน 50
                        ตัวอักษร</p>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Project Type</label>
                <?php $this->tag->setDefault("project_type", $selectProject->project_type); ?>
                <div class="col-sm-2">
                    <?php

                    echo $this->tag->selectStatic(array(
                        "project_type",
                        "class" => "form-control",
                        "required" => "",
                        array("Software" => "Software", "Hardware" => "Hardware", "SW-HW" => "SW-HW")
                    ));

                    ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Semester</label>
                <?php

                $semester = $selectProject->Semester;

                ?>
                <div class="col-sm-2">
                    <p class="form-control-static"><?= $semester->semester_term ?>/<?= $semester->semester_year ?></p>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Create By</label>

                <div class="col-sm-10">
                    <p class="form-control-static">
                        <?php

                        $projectMaps = $selectProject->ProjectMap;

                        foreach ($projectMaps as $projectMap)
                        {
                            if ($projectMap->map_type != 'owner')
                                continue;

                            ?>
                            <a href="<?= $this->url->get('profile/index/') . $projectMap->User->id; ?>"><?= $projectMap->User->title . $projectMap->User->name; ?></a>
                            <?php
                        }
                        ?>
                    </p>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Advisor</label>

                <div class="col-sm-10">
                    <?php

                    foreach ($projectMaps as $projectMap)
                    {
                        if ($projectMap->map_type == 'advisor')
                        {
                            ?>
                            <p class="form-control-static"><?= $projectMap->User->title . $projectMap->User->name ?></p>
                            <?php

                            break;
                        }
                    }
                    ?>

                </div>
            </div>
            <?php
            foreach ($projectMaps as $projectMap)
            {
                if ($projectMap->map_type != 'coadvisor')
                    continue;
                ?>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Co-Advisor</label>

                    <div class="col-sm-10">
                        <p class="form-control-static"><?= $projectMap->User->title . $projectMap->User->name ?></p>
                    </div>
                </div>
                <?php
            }
            ?>
            <div class="form-group">
                <label class="col-sm-2 control-label">Project Level</label>

                <div class="col-sm-10">
                    <p class="form-control-static"><?= $selectProject->ProjectLevel->project_level_name ?></p>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Description</label>

                <div class="col-sm-10">
                    <textarea id="description" name="description"><?= $selectProject->project_description ?></textarea>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-sm btn-primary">Apply</button>
                </div>
            </div>
            <br>
            <?php
            if ($auth['type'] == 'Advisor' || $auth['type'] == 'Admin')
            {
            if ($selectProject->project_status == 'Pending')
            {
                ?>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Proposed Project</label>


                    <input type="hidden" id="reason" name="reason" value="">
                    <input type="hidden" name="project_id" value="<?= $selectProject->project_id; ?>">
                    <div class="col-sm-10">
                        <a class="btn btn-sm btn-success"
                           href="<?= $this->url->get('projects/accept/') . $selectProject->project_id; ?>"
                           onclick="return confirm('Confirm accept');">Accept</a>
                        <button class="btn btn-sm btn-danger"
                                formaction="<?= $this->url->get('projects/reject'); ?>"
                                onclick="return confirmReject();">
                            Reject
                        </button>
                    </div>
                </div>

                <br>
                <br>
                <?php
            }
            ?>
        </form>


        <script>
            function confirmReject() {
                var promptBox = prompt("ยินยันการลบโครงงาน (กรอกเหตุผล optional)");

                if (promptBox != null) {
                    $("#reason").attr('value', promptBox);
                    return true;
                }

                return false;
            }
        </script>

        <center>
            <h3>Delete whole project</h3>
            <button class="btn btn-danger btn-sm" id="show">Delete</button>
        </center>
    <br>
        <div class="panel panel-danger" id="panel">
            <div class="panel-heading">
                <h3 class="panel-title">Delete whole project</h3>
            </div>
            <div class="panel-body">
                <h3>Delete project cannot be restored!</h3>

                <form method="post" action="<?= $this->url->get('projects/delete'); ?>">
                    <input type="hidden" value="<?= $params[0]; ?>" name="pid">
                    <?=
                    $this->tag->textField(array('comment', 'class' => 'form-control', 'placeholder' => 'เหตุผลที่ลบ'));
                    ?>
                    <br>
                    <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('ยืนยันการลบโครงงาน');">
                        Delete
                    </button>
                </form>
            </div>
        </div>
        <script>
            $("#panel").toggle();
            $(document).ready(function () {
                $("#show").click(function () {
                    $("#panel").fadeToggle();
                });
            });
        </script>
    <?php
    }
    ?>
    </div>
</div>
