<?php

echo $this->getContent();
$auth = $this->session->get('auth');
$user_id = $auth['id'];

?>

<div class="row">
    <div class="col-sm-3">
        <div class="list-group">
            <a href="#" class="list-group-item active">
                <h4 class="list-group-item-heading">Project</h4>
            </a>
            <?php

            $projectMaps = ProjectMap::find(array(
                "conditions" => "user_id=:user_id:",
                "order" => "project_id DESC",
                "bind" => array("user_id" => $user_id)
            ));

            foreach ($projectMaps as $projectMap)
            {
                $project = Project::findFirst(array(
                    "conditions" => "project_id=:project_id:",
                    "bind" => array("project_id" => $projectMap->project_id)
                ));

                echo '<a href="' . $this->url->get('projects/manage/') . $project->project_id . '" class="list-group-item">';
                echo $project->project_name;
                echo '</a>';
            }

            ?>
            </ul>
        </div>
    </div>
</div>
