<?php

echo $this->getContent();
$auth = $this->session->get('auth');
$user_id = $auth['id'];
$project_id = $this->dispatcher->getParam(0);

?>

<div class="col-sm-3">
    <div class="list-group">
        <a href="#" class="list-group-item active">
            <h4 class="list-group-item-heading">Project</h4>
        </a>
        <?php

        foreach ($projects as $project)
        {
            if ($project->project_id == $project_id)
                $str = "list-group-item-success";
            else
                $str = '';


            ?>
            <a href="<?= $this->url->get('projects/manage/').$project->project_id; ?>" class="list-group-item <?= $str; ?>">
                <?=  $project->project_name . ' (' . $project->Semester->semester_term . '/' . $project->Semester->semester_year . ')'; ?>
            </a>

        <?php
        }

        ?>
    </div>
</div>
