<?php

echo $this->getContent();
$auth = $this->session->get('auth');
$user_id = $auth['id'];

if (!$selectProject)
{
    $this->flashSession->error('Project not found');
    $this->response->redirect('projects/me');
}

$e = new Phalcon\Escaper();

?>

<div class="row">
    <?php require(__DIR__ . '/../layouts/projectHeader.php'); ?>

    <div class="tab-content">
        <div class="tab-pane fade in active" id="setting">
            <br>
            <?php

            if ($selectProject->project_status == 'Accept')
            {
            }
            else
            {
                ?>
                <a href="<?= $this->url->get('projects/addmember/'); ?><?= $selectProject->project_id; ?>"
                   class="btn btn-success btn-sm pull-right">New Project Member</a>
                <br>
                <br>
                <?php
            }
            ?>
            <table class="table" width="100%">
                <thead>
                <tr class="success">
                    <th><?= $selectProject->project_name ?> project member</th>
                    <th width="5%"></th>
                </tr>
                </thead>
                <tbody>
                <?php

                $projectMaps = ProjectMap::find("project_id='$params[0]' AND map_type='owner'");
                foreach ($projectMaps as $projectMap)
                {
                    $user = User::findFirst("id='$projectMap->user_id'");

                    if (file_exists(__DIR__ . '/../../../public/profilePicture/' . $user->user_id . '.jpg'))
                        $imgSrc = $url . 'profilePicture/' . $user->user_id . '.jpg';
                    else
                        $imgSrc = $url . 'profilePicture/noface.jpg';

                    echo '<tr>';
                    echo '<td class="active">';
                    echo '<div class="col-sm-1">';

                    echo '<img src="' . $imgSrc;
                    echo '" width="50px" height="50px">';
                    echo '</div>';

                    echo '<div class="col-sm-10">';
                    echo '<a href="' . $this->url->get('profile/index/') . $user->id . '">';
                    echo $user->title . $user->name;
                    echo '</a><br>' . $user->user_id;
                    echo '</div>';
                    echo '</td>';
                    echo '<td class="active">';
                    if ($selectProject->roject_status == "Accept" || $user->id == $user_id)
                    {
                    }
                    else
                    {
                        echo '<a href="' . $this->url->get('projects/deletemember/');
                        echo $params[0] . '/' . $projectMap->project_map_id;
                        echo '" class="btn btn-danger btn-xs" onclick="return confirm (\'ยืนยันการลบ\');">';
                        echo 'Delete';
                        echo '</a>';
                    }
                    echo '</td>';
                    echo '</tr>';
                }

                ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
</div>
