<?= $this->getContent(); ?>

<?php

if (!$canCreateProject)
    return false;

?>

<script type="text/javascript">

    tinymce.init({
        selector: "textarea#description",
        plugins: [
            "advlist autolink lists link image charmap print preview hr anchor pagebreak",
            "searchreplace wordcount visualblocks visualchars code fullscreen",

            "insertdatetime media nonbreaking save table contextmenu directionality",
            "template paste textcolor"
        ],
        toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image print preview media | forecolor backcolor emoticons",
        image_advtab: true,
        autosave_ask_before_unload: false,
        width: "80%",
        height: "200px"
    });
</script>

<h4>Create Project</h4>

<hr>

<form class="form-horizontal" method="post" action="<?= $url . 'projects/doNewProject'; ?>">
    <div id="first-step">
        <div class="form-group">
            <label class="col-sm-2 control-label">Semester</label>
            <div class="col-sm-10">
                <p class="form-control-static"><?= $current_semester; ?></p>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">Project Level</label>
            <div class="col-sm-10">
                <p class="form-control-static"><?= $project_level_name; ?></p>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">Advisor</label>
            <div class="col-sm-3">
                <?php

                echo \Phalcon\Tag::selectStatic(array(
                    'advisor_id',
                    $advisors,
                    'class' => 'form-control',
                    'required' => 'required'
                ));

                ?>
            </div>
            <div class="col-sm-7">
                <p class="form-control-static" id="quotaText"></p>
            </div>
        </div>
    </div>
    <div id="second-step">
        <div class="form-group">
            <label class="col-sm-2 control-label">Project Name</label>
            <div class="col-sm-6">
                <?php

                echo \Phalcon\Tag::textField(array(
                    'project_name',
                    'class' => 'form-control',
                    'required' => 'required',
                    'maxlength' => '250'
                ))



                ?>

                <p class="help-block">ใส่เฉพาะชื่อภาษาไทย <strong>หรือ</strong> ภาษาอังกฤษ จำกัดความยาวไม่เกิน 250
                    อักขระ</p>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">Project Type</label>
            <div class="col-sm-2">
                <?php

                echo \Phalcon\Tag::selectStatic(array(
                    'project_type',
                    array(
                        'Software' => 'Software',
                        'Hardware' => 'Hardware',
                        'SW-HW' => 'SW-HW'
                    ),
                    'class' => 'form-control',
                    'required' => 'required'
                ));

                ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">Description</label>

            <div class="col-sm-10">
                <?= \Phalcon\Tag::textArea('description'); ?>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary btn-sm">Create Project</button>
            </div>
        </div>
    </div>
</form>

<script>
    $(document).ready(function () {
        var obj = $('#advisor_id');
        var quotaText = $('#quotaText');
        var advisor_id = obj.val();

        var secondStep = $('#second-step');
        secondStep.hide();

        getQuota();

        obj.change(function () {
            advisor_id = this.value;
            getQuota();
        });

        function getQuota() {
            quotaText.html("<div style=\"color: orange\">Loading...</div>")

            $.get("<?= $url . 'advisor/checkQuota/'; ?>" + advisor_id)
                .success(function (data) {
                    var jOBJ = JSON.parse(data);

                    if (jOBJ.quota > 5) {
                        quotaText.html("<div style=\"color: green\">สามารถรับได้อีก " + jOBJ.quota + " โครงงาน (รอยืนยัน " + jOBJ.pending + " โครงงาน)</div>");
                        secondStep.show();
                    }
                    else if (jOBJ.quota > 0) {
                        quotaText.html("<div style=\"color: orange\">สามารถรับได้อีก " + jOBJ.quota + " โครงงาน (รอยืนยัน " + jOBJ.pending + " โครงงาน)</div>");
                        secondStep.show();
                    }
                    else {
                        quotaText.html("<div style=\"color: red\">ไม่สามารถรับนักศึกษาได้แล้ว (รอยืนยัน " + jOBJ.pending + " โครงงาน)</div>");
                        secondStep.hide();
                    }
                });
        }
    });
</script>
