<?php 

echo $this->getContent();
$auth = $this->session->get('auth');
$user_id = $auth['id'];

$projectMaps = ProjectMap::find("user_id='$user_id' AND map_type='advisor'");

$found = false;

foreach ($projectMaps as $projectMap)
{
    $project = Project::findFirst("project_id='$projectMap->project_id' AND project_status='Pending'");

    if (!$project)
        continue;

	$found = true;

    ?>
    <div class="panel panel-info" style="display: block;">
        <div class="panel-heading">
           <h3 class="panel-title">โครงงาน <?= $project->project_name ?></h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <label class="col-sm-2">Project Name</label>
                <p class="col-sm-10"><?= $project->project_name ?></p>
            </div>
			<div class="row">
				<label class="col-sm-2">Create By</label>
				<p class="col-sm-10">
				<?php

				$projectMaps = ProjectMap::find("project_id='$project->project_id' AND map_type='owner'");

				for ($i = 0 ; $i < count($projectMaps) ; $i++)
				{
					if ($i != 0)
						echo '<br>';
					$tuid = $projectMaps[$i]->user_id;
					$student = User::findFirst("id='$tuid'");
					echo $student->title.$student->name;
				}

				?>
				</p>
			</div>
            <div class="row">
                <label class="col-sm-2">Project Type</label>
                <p class="col-sm-10"><?= $project->project_type ?></p>
            </div>
            <div class="row">
                <label class="col-sm-2">Project Level</label>
                <?php
                $projectLevel = ProjectLevel::findFirst("project_level_id='$project->project_level_id'");
                ?>
                <p class="col-sm-10"><?= $projectLevel->project_level_name ?></p>
            </div>
            <div class="row">
                <label class="col-sm-2">Semester</label>
                <?php
                $semester = Semester::findFirst("semester_id='$project->semester_id'");
                ?>
                <p class="col-sm-10"><?= $semester->semester_term?>/<?= $semester->semester_year?></p>
            </div>
            <div class="row">
                <label class="col-sm-2">Project Details</label>
                <div class="col-sm-10">
                    <a href="<?= $this->url->get('projects/manage/'); ?><?= $project->project_id ?>" class="btn btn-xs btn-info" target="_blank">Show</a>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-2"></label>
                <div class="col-sm-offset-2 col-sm-10">
                    <a href="<?= $this->url->get('projects/accept/'); ?><?= $project->project_id ?>" class="btn btn-xs btn-success">Accept</a>
                    <a href="<?= $this->url->get('projects/reject/'); ?><?= $project->project_id ?>" class="btn btn-xs btn-danger" onclick="return confirm('ยืนยันการลบโครงงาน'); ">Reject</a>
                </div>
            </div>
        </div>
    </div>
    <?php
}

if (!$found)
	$this->flash->notice('ยังไม่มีโครงงานให้เลือก');

?>
