<?php
$params = $this->dispatcher->getParams();

$status = $reportComments[count($reportComments) - 1]->status;

if ($status != 'Accept')
    $alert = "alert alert-warning";
else
    $alert = "alert alert-success";
?>


<div class="row">
    <?php require(__DIR__ . '/../layouts/projectHeader.php'); ?>
    <div class="tab-content">
        <div class="tab-pane fade in active" id="progress">

            <br>

            <div class="<?= $alert; ?>">
                สถานะปัจจุบัน <?= $reportComments[count($reportComments) - 1]->status; ?>
            </div>

            <?php

            if ($status != 'Accept'):

                ?>

                <div class="pull-right">
                    <a href="<?= $this->url->get('report/upload/'); ?><?= $params[0] ?>"
                       class="btn btn-xs btn-success">Upload Report</a>
                </div>

                <br>
                <br>

                <?php

            endif;

            ?>


            <br>


            <table class="table" width="100%">
                <tr class="success">
                    <th><?= $selectProject->project_name; ?>'s Report</th>
                </tr>
                <tr>
                    <?php

                    if (!$foundReport):

                        ?>
                        <td>ไม่พบข้อมูล</td>
                        <?php
                    else:
                        ?>
                        <td>
                            รายงานอัพเดตเวลา <?= $reportComments[count($reportComments) - 1]->create_date; ?>
                            <div class="pull-right">
                                <a href="<?= $url . 'report/download/' . $project->project_id; ?>">
                                    Download
                                </a>
                            </div>
                        </td>

                        <?php

                    endif;
                    ?>
                </tr>
            </table>

            <table class="table" width="100%">
                <tr class="success">
                    <th>Report's Logs</th>
                </tr>

                <?php

                foreach ($reportComments as $reportComment):

                    ?>
                    <tr>
                        <td>
                            <?= $reportComment->comment; ?>
                        </td>
                    </tr>

                    <?php

                endforeach;
                ?>


            </table>


        </div>
    </div>
</div>
</div>
