<?php

$params = $this->dispatcher->getParams();
?>


<div class="row">
    <?php require(__DIR__ . '/../layouts/projectHeader.php'); ?>
    <div class="tab-content">
        <div class="tab-pane fade in active" id="progress">

            <br>

            <?php $this->flash->warning('คำเตือน: ระบบจะบันทึกรายงานฉบับล่าสุด และรับเฉพาะไฟล์ pdf เท่านั้น'); ?>

            <form class="form-horizontal" method="post" enctype="multipart/form-data" action="<?= $url.'report/doUpload'; ?>">
                <?=

                \Phalcon\Tag::hiddenField(array(
                    'project_id',
                    'value' => $selectProject->project_id
                ));

                ?>

                <div class="form-group">
                    <label class="col-sm-2 control-label">ไฟล์รายงาน</label>

                    <div class="col-sm-10">
                        <?=

                        \Phalcon\Tag::fileField(array(
                            'report',
                            'required' => 'required',
                            'class' => 'form-control-static'
                        ));

                        ?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button class="btn btn-sm btn-primary" type="submit">Upload</button>
                    </div>
                </div>

            </form>
        </div>
    </div>
</div>
</div>
