<?php echo $this->getContent(); ?>

<div class="row">
    <form class="form-horizontal" method="post" action="<?= $this->url->get('exam/generate'); ?>">
        <div class="form-group">
            <label class="col-sm-3 control-label">สร้างตารางสอบ</label>

            <div class="col-sm-2">
                <?php

                $this->tag->setDefault('semester_id', $currentSemesterId);

                echo $this->tag->selectStatic(array(
                    'semester_id',
                    $allSemesters,
                    'class' => 'form-control',
                    'required' => 'required'
                ));

                ?>
            </div>
            <div class="col-sm-2">
                <button type="submit" class="btn btn-primary btn-sm">สร้างตารางสอบ</button>
            </div>
        </div>
    </form>
</div>
<div class="row">
    <form class="form-horizontal" method="post" action="<?= $this->url->get('exam/edit'); ?>">
        <div class="form-group">
            <label class="col-sm-3 control-label">ดูตารางสอบ</label>

            <div class="col-sm-2">
                <?php
                echo $this->tag->selectStatic(array(
                    'semester_id',
                    $allSemesters,
                    'class' => 'form-control',
                    'required' => 'required'
                ));

                ?>
            </div>
            <div class="col-sm-2">
                <button type="submit" class="btn btn-sm btn-primary">ดูตารางสอบที่เผยแพร่</button>
            </div>
        </div>
    </form>
</div>
<div class="row">
    <form class="form-horizontal" method="post" action="<?= $this->url->get('exam/upload'); ?>">
        <div class="form-group">
            <label class="col-sm-3 control-label">อัพโหลดตารางสอบ</label>

            <div class="col-sm-2">
                <button type="submit" class="btn btn-sm btn-primary">อัพโหลดตารางสอบ</button>
            </div>
        </div>
    </form>
</div>

<br>
<br>

<div class="alert alert-info">
    <h4>คำอธิบาย</h4>
    <ul>
        <li>
            <p><strong>สร้างตารางสอบ</strong> เป็นการสร้างไฟล์ template จากข้อมูลในระบบ เพื่อให้นำไปแก้ไขวันที่
                เวลาและห้องที่ใช้ในการสอบ</p>
        </li>
        <li>
            <p><strong>ดูตารางสอบ</strong> เป็นการดูตารางสอบที่่ ผู้ใช้งานคนอื่นเห็นในระบบ</p>
        </li>
        <li>
            <p><strong>อัพโหลดตารางสอบ</strong> เป็นการแก้ไขตารางสอบปัจจุบัน
                โดยผู้ใช้งานคนอื่นจะเห็นตารางสอบที่ทำการอัพโหลด</p>
        </li>
    </ul>
</div>
