<?php echo $this->getContent(); ?>

<div class="row">
    <table width="100%">
        <tr>
            <td width="30%">
                <a href="<?= $this->url->get('exam/generate'); ?>" class="btn btn-primary btn-lg btn-block">
                    สร้าง<br>ตารางสอบ
                </a>
            </td>
            <td width="5%"></td>
            <td width="30%">
                <a href="<?= $this->url->get('exam/edit'); ?>" class="btn btn-primary btn-lg btn-block">
                    ดูตารางสอบ<br>ที่เผยแพร่
                </a>
            </td>
            <td width="5%"></td>
            <td width="30%">
                <a href="<?= $this->url->get('exam/upload'); ?>" class="btn btn-primary btn-lg btn-block">
                    อัพโหลด<br>ตารางสอบ
                </a>
            </td>
        </tr>
    </table>
</div>

<br>
<br>

<div class="alert alert-info">
    <h4>คำอธิบาย</h4>
    <ul>
        <li>
            <p><strong>สร้างตารางสอบ</strong> เป็นการสร้างไฟล์ template จากข้อมูลในระบบ เพื่อให้นำไปแก้ไขวันที่
                เวลาและห้องที่ใช้ในการสอบ</p>
        </li>
        <li>
            <p><strong>ดูตารางสอบ</strong> เป็นการดูตารางสอบที่่ ผู้ใช้งานคนอื่นเห็นในระบบ</p>
        </li>
        <li>
            <p><strong>อัพโหลดตารางสอบ</strong> เป็นการแก้ไขตารางสอบปัจจุบัน
                โดยผู้ใช้งานคนอื่นจะเห็นตารางสอบที่ทำการอัพโหลด</p>
        </li>
    </ul>
</div>
