<?php

echo $this->getContent();

$this->flash->warning('คำเตือน: ระบบจะเก็บไฟล์ล่าสุดเท่านั้น');

?>

<h4>อัพโหลดตารางสอบ</h4>

<form class="form-horizontal" method="post" enctype="multipart/form-data"
      action="<?= $this->url->get('exam/doUpload'); ?>">
    <div class="form-group">
        <div class="col-sm-2">
            <?php

            $this->tag->setDefault('semester_id', $currentSemesterId);

            echo $this->tag->selectStatic(array(
                'semester_id',
                $allSemesters,
                'required' => 'required',
                'class' => 'form-control'
            ));

            ?>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-2">
            <?= Phalcon\Tag::filefield("examfile"); ?>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('ยืนยันการอัพโหลด')">
                อัพโหลด
            </button>
            <a href="<?= $this->url->get('exam/manage'); ?>" class="btn btn-warning btn-sm">ยกเลิก</a>
        </div>
    </div>
</form>
