<?php echo $this->getContent() ?>
<?php use Phalcon\Tag as Tag; ?>

<?php

//check auth
$auth = $this->session->get('auth');
$params = $this->dispatcher->getParams();
if (empty($params[0]))
    $params[0] = 0;
$user = User::findFirst("id='$params[0]'");
$projectMaps = ProjectMap::find("user_id='$params[0]'");

?>
<br>

<div class="row">
    <div class="col-sm-5">
        <?php

        if (file_exists(__DIR__.'/../../public/profilePicture/'.$user->user_id.'.img'))
            $imgSrc = $url.'profilePicture/'.$user->user_id.'.img';
        else
            $imgSrc = $url.'profilePicture/noface.img';

        ?>

        <div class="text-center">
            <img src="<?= $imgSrc ?>" class="bordered" width="150" height="150"><br><br>
            <?php
            if ($params[0] == $auth['id'])
            {
                ?>
                <a href="<?= $this->url->get('profile/updateProfile'); ?>" class="btn btn-success btn-sm">Edit
                    Profile</a>
            <?php
            }
            ?>
        </div>
    </div>

    <div class="col-sm-7">
        <div class="row">
            <label class="col-sm-3">Name: </label>

            <div class="col-sm-9">
                <?= $user->title ?><?= $user->name ?>
            </div>
        </div>

    
        <div class="row">
            <label class="col-sm-3">Tel: </label>

            <div class="col-sm-9">
                <?= $user->tel; ?>
            </div>
        </div>


        <div class="row">
            <label class="col-sm-3">Facebook: </label>

            <div class="col-sm-9">
                <a href="https://www.facebook.com/<?= $user->facebook; ?>"
                   target="_blank">https://www.facebook.com/<?= $user->facebook; ?></a>
            </div>
        </div>

        <div class="row">
            <label class="col-sm-3">Email: </label>

            <div class="col-sm-9">
                <a href="mailto:<?= $user->email; ?>"><?= $user->email; ?></a>
            </div>
        </div>

        <div class="row">
            <label class="col-sm-3">Interesting: </label>

            <div class="col-sm-9">
                <?= $user->interesting ?>
            </div>
        </div>

        <?php
        if ($user->type == 'Advisor')
        {
            ?>
            <div class="row">
                <label class="col-sm-10">Project Advising: </label>
            </div>
            <div class="row">
                <div class="col-sm-offset-3 col-sm-10">
                    <?php
                    foreach ($projectMaps as $projectMap)
                    {
                        if ($projectMap->map_type == 'advisor')
                        {
                            $project = Project::findFirst(array(
                                "conditions" => "project_id=:project_id: AND project_status='Accept' AND semester_id=:semester_id:",
                                "bind" => array(
                                    "project_id" => $projectMap->project_id,
                                    "semester_id" => $currentSemesterId
                                )
                            ));
                            if (!$project)
                                continue;
                            echo $project->project_name;
                            echo '<br>';
                        }
                    }
                    ?>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-10">Project Co-advising: </label>
            </div>
            <div class="row">
                <div class="col-sm-offset-3 col-sm-10">
                    <?php

                    foreach ($projectMaps as $projectMap)
                    {
                        if ($projectMap->map_type == 'coadvisor')
                        {
                            $project = Project::findFirst(array(
                                "conditions" => "project_id=:project_id: AND project_status='Accept' AND semester_id=:semester_id:",
                                "bind" => array(
                                    "project_id" => $projectMap->project_id,
                                    "semester_id" => $currentSemesterId
                                )
                            ));
                            if (!$project)
                                continue;
                            echo $project->project_name;
                            echo '<br>';
                        }
                    }
                    ?>
                </div>
            </div>

            <a href="#" id="showhide">Show/Hide project all semester</a><br><br>

            <div class="panel panel-info" id="allproject">
                <div class="panel panel-body">
                    <?php

                    $count = 0;

                    foreach ($allSemesters as $allSemester)
                    {
                        ?>
                        <h3><?= $allSemester; ?></h3>
                        <?php
                        foreach ($projectMaps as $projectMap)
                        {
                            if ($projectMap->map_type == 'advisor')
                            {
                                $project = Project::findFirst(array(
                                    "conditions" => "project_id=:project_id: AND project_status='Accept' AND semester_id=:semester_id:",
                                    "bind" => array(
                                        "project_id" => $projectMap->project_id,
                                        "semester_id" => $allSemesterIds[$count]
                                    )
                                ));
                                if (!$project)
                                    continue;
                                echo $project->project_name;
                                echo '<br>';
                            }
                        }
                        ?>
                        <?php
                        $count++;
                    }

                    ?>
                </div>
            </div>

            <script>
                $(document).ready(function () {
                    $('#allproject').hide();

                    $("#showhide").click(function () {
                        $('#allproject').toggle(1000);
                    });
                });
            </script>

        <?php
        }
        else
        {
        ?>
            <div class="row">
                <label class="col-sm-3">Project: </label>

                <div class="col-sm-9">
                    <?php
                    foreach ($projectMaps as $projectMap)
                    {
                        if ($projectMap->map_type == 'owner')
                        {
                            $project = Project::findFirst("project_id='$projectMap->project_id'");
                            echo $project->project_name;
                            echo '<br>';
                        }
                    }
                    ?>
                </div>
            </div>
        <?php
        }
        ?>
    </div>
</div>
