<?= $this->getContent(); ?>

<ul class="nav nav-tabs" id="verifyEmailTab">
    <li role="presentation" class="active">
        <a href="#verifyEmail" aria-controls="verifyEmail" role="tab" data-toggle="tab">
            Verify Email
        </a>
    </li>
</ul>

<div class="tab-content">
    <div role="tabpanel" class="tab-pane fade in active" id="verifyEmail">
        <form class="form-horizontal" role="form" method="post"
              action="<?= $this->url->get('profile/confirmActivateCode'); ?>">
            <div class="form-group">

                <label class="control-label col-sm-2">Email</label>

                <div class="col-sm-10">
                    <div class="form-control-static">
                        <?= $user->email; ?>
                        <button type="button" id="sendbtn" class="btn btn-primary btn-sm form-control-static"
                                onclick="sendActivateCode();">Send verify email
                        </button>
                    </div>
                </div>

            </div>

            <div class="form-group">
                <label class="control-label col-sm-2">Activate code</label>

                <div class="col-sm-2">
                    <?php

                    echo \Phalcon\Tag::textField(array(
                        "activate_code",
                        "required" => "required",
                        "class" => "form-control"
                    ));

                    ?>
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-success btn-sm">Activate</button>
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    function sendActivateCode() {
        $('#sendbtn').prop('disabled', true);

        $.get("<?= $this->url->get('profile/sendActivateCode'); ?>", function () {
            alert("Activation code has been send");
        });

        $('#sendbtn').prop('disabled', false);
    }
</script>