<?php

echo $this->getContent();
$auth = $this->session->get('auth');
$user_id = $auth['id'];

$newss = News::find(array("order" => "id DESC", "limit" => 8));

?>

<div class="row">
    <div class="col-sm-3">
        <a href="<?= $this->url->get('projects/proposed'); ?>" class="btn btn-primary btn-lg btn-block">
            Proposed<br>Project
        </a>
    </div>
    <div class="col-sm-3">

        <a href="<?= $this->url->get('exam/showExam'); ?>" class="btn btn-primary btn-lg btn-block">
            Exam<br>Schedule
        </a>
    </div>
    <div class="col-sm-3">
        <a href="<?= $this->url->get('room/proposed'); ?>" class="btn btn-primary btn-lg btn-block">
            Proposed<br>Room Request
        </a>
    </div>
    <div class="col-sm-3">
        <a href="<?= $this->url->get(); ?>" class="btn btn-primary btn-lg btn-block">
            Manage<br>Student
        </a>
    </div>
</div>

<br>

<h4>News</h4>
<div class="panel panel-info">
    <div class="panel-body">
        <ul>
            <?php

            foreach ($newss as $news)
            {
                ?>
                <li><?= $news->create_date . ' ' . $news->news; ?></li>
                <?php
            }

            ?>
        </ul>
    </div>
</div>

<h4>Event Update</h4>
<div class="panel panel-info">
    <div class="panel-body">
        <?php

        $logs = Log::find(array("conditions" => "user_id='$user_id'", "order" => "create_date DESC", "limit" => 8));

        echo '<ul>';
        foreach ($logs as $log)
        {
            echo '<li>' . $log->create_date . ' ' . $log->description . '</li>';
        }
        echo '</ul>';

        ?>
    </div>
</div>
