<?php

echo $this->getContent();
$auth = $this->session->get('auth');
$user_id = $auth['id'];

$newss = News::find(array("order" => "id DESC", "limit" => 8));

?>

<table width="100%">
    <tr>
        <td width="30%">
            <a href="<?= $this->url->get('projects/proposed'); ?>" class="btn btn-primary btn-lg btn-block">
                Proposed<br>Project
            </a>
        </td>
        <td width="5%"></td>
        <td width="30%">
            <a href="<?= $this->url->get('exam/showExam'); ?>" class="btn btn-primary btn-lg btn-block">
                Exam<br>Schedule
            </a>
        </td>
        <td width="5%"></td>
        <td width="30%">
            <a href="<?= $this->url->get('score/advisorView'); ?>" class="btn btn-primary btn-lg btn-block">
                View<br>Score
            </a>
        </td>
    </tr>
</table>

<br>

<h4>News</h4>
<div class="panel panel-info">
	<div class="panel-body">
		<ul>
			<?php

			foreach ($newss as $news)
			{
				?>
				<li><?= $news->create_date.' '.$news->news; ?></li>
				<?php
			}

			?>
		</ul>
	</div>
</div>

<h4>Log</h4>
<div class="panel panel-info">
	<div class="panel-body">
		<?php

		$logs = Log::find(array("conditions" => "user_id='$user_id'", "order" => "create_date DESC", "limit" => 8));

		echo '<ul>';
		foreach ($logs as $log)
		{
			echo '<li>'.$log->create_date.' '.$log->description.'</li>';
		}
		echo '</ul>';

		?>
	</div>
</div>
