<?php echo $this->getContent(); ?>

<div class="col-sm-3 sidebar">
    <div class="list-group">
        <a class="list-group-item active">
            <h4 class="list-group-item-heading">Advisors</h4>
        </a>

        <?php
        

        foreach ($advisors as $user):

            ?>

            <a class="list-group-item <?= ($this->dispatcher->getParam(0) == $user->id) ? 'list-group-item-success' : ''; ?>"
               href="<?= $url . 'advisor/profile/' . $user->id; ?>"><?= $user->title . $user->name; ?></a>

            <?php

        endforeach;

        ?>
    </div>
</div>

