<?php

echo $this->getContent();

$advisors = User::find("type='Advisor'");
$auth = $this->session->get('auth');
$user_id = $auth['id'];

//show all config for admin otherwise show only user
if ($auth['type'] != 'Admin')
    $advisors = User::find("type='Advisor' AND id='$user_id'");

?>

<style>
    th, .tcenter
    {
        text-align: center;
    }
</style>

<div class="row">
    <form method="post" action="<?= $this->url->get('advisor/setQuota'); ?>">
        <table width="100%" class="table">
            <thead>
            <tr class="success">
                <th>อาจารย์ที่ปรึกษา</th>
                <th width="20%">
                    จำนวนที่รับได้
                </th>
                <th width="20%">
                    จำนวนที่รับแล้ว
                </th>
                <th width="20%">
                    จำนวนที่รอยืนยัน
                </th>
            </tr>
            </thead>
            <tbody>
            <?php

            $totalAC = 0;
            $totalPD = 0;

            foreach ($advisors as $advisor)
            {
                $quota = Quota::findFirst("advisor_id='$advisor->id'");

                ?>
                <tr>
                    <td><?= $advisor->title . $advisor->name; ?></td>
                    <td>
                        <?=
                        $this->tag->numericField(array(
                                'quota[]',
                                'class' => 'form-control',
                                'value' => $quota->quota_pp
                            ));
                        ?>
                        <input type="hidden" name="id[]" value="<?= $quota->advisor_id; ?>">
                    </td>
                    <td class="tcenter">
                            <?php


                            $ac =  $this->CheckQuota->acceptProject($advisor->id, $currentSemesterId);
                            $totalAC += $ac;
                            echo $ac

                            ?>
                    </td>
                    <td class="tcenter">
                            <?php

                            $pd = $this->CheckQuota->pendingProject($advisor->id, $currentSemesterId);
                            $totalPD += $pd;
                            echo $pd;

                            ?>
                    </td>
                </tr>
            <?php
            }

            ?>

            <tr>
                <td>รวม</td>
                <td></td>
                <td class="tcenter"><?= $totalAC; ?></td>
                <td class="tcenter"><?= $totalPD; ?></td>
            </tr>
            </tbody>
        </table>
        <button type="submit" class="btn btn-sm btn-success">บันทึก</button>
    </form>
</div>

