<?php

$auth = $this->session->get('auth');
$action = $this->dispatcher->getActionName();
$controller = $this->dispatcher->getControllerName();

if (!defined('LISTSELECTED'))
define('LISTSELECTED', 'list-group-item-success');

?>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?= $this->url->get('index'); ?>">CoE-Project</a>
        </div>
        <div class="navbar-collapse collapse">
            <?php echo $this->elements->getMenu(); ?>
        </div>
    </div>
</nav>

<div class="container">
    <div class="row">
        <div class="col-sm-3 sidebar">
            <div class="list-group">
                <a class="list-group-item active" href="#">
                    <h4 class="list-group-item-heading">Menu</h4>
                </a>
                <a class="list-group-item <?= ($controller == 'admin' && $action == 'summaryTopic') ? LISTSELECTED : ''; ?>"
                   href="<?= $this->url->get('admin/summaryTopic'); ?>">สรุปหัวข้อโครงงาน</a>
                <a class="list-group-item <?= ($controller == 'exam' && $action == 'manage') ? LISTSELECTED : ''; ?>"
                   href="<?= $this->url->get('exam/manage'); ?>">จัดการตารางสอบ</a>
                <a class="list-group-item <?= ($controller == 'enroll') ? LISTSELECTED: ''; ?>"
                   href="<?= $this->url->get('enroll'); ?>">จัดการผู้เรียน</a>
                <a class="list-group-item <?= ($controller == 'advisor' && $action == 'manageAdvisor') ? LISTSELECTED : ''; ?>"
                   href="<?= $this->url->get('advisor/manageAdvisor'); ?>">จัดการอาจารย์ที่ปรึกษา</a>
                <a class="list-group-item <?= ($controller == 'admin' && $action == 'manageCoadvisor') ? LISTSELECTED : ''; ?>"
                   href="<?= $this->url->get('admin/manageCoadvisor'); ?>">จัดการอาจารย์ที่ปรึกษาร่วม</a>
                <a class="list-group-item <?= ($controller == 'advisor' && $action == 'quota') ? LISTSELECTED : ''; ?>"
                   href="<?= $this->url->get('advisor/quota'); ?>">จัดการโควต้า</a>
                <a class="list-group-item <?= ($controller == 'admin' && $action == 'changeRole') ? LISTSELECTED : ''; ?>"
                   href="<?= $this->url->get('admin/changeRole'); ?>">เปลี่ยนสิทธิ์การใช้งาน</a>
                <a class="list-group-item <?= ($controller == 'news' && $action == 'manageNews') ? LISTSELECTED : ''; ?>"
                   href="<?= $this->url->get('news/manageNews'); ?>">จัดการข่าว</a>
                <a class="list-group-item <?= ($controller == 'admin' && $action == 'setView') ? LISTSELECTED : ''; ?>"
                   href="<?= $this->url->get('admin/setView'); ?>">เปลี่ยนมุมมอง</a>
                <a class="list-group-item <?= ($controller == 'settings') ? LISTSELECTED : ''; ?>"
                   href="<?= $this->url->get('settings'); ?>">ตั้งค่าระบบ</a>

            </div>
        </div>
        <div class="col-sm-9">
            <?php echo $this->getContent(); ?>
        </div>
    </div>
</div>

