<?php
$auth = $this->session->get('auth');
$user_id = $auth['id'];
$projectMaps = ProjectMap::find("user_id='$user_id' AND map_type='advisor'");
?>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?= $this->url->get('index'); ?>">CoE-Project</a>
        </div>
        <div class="navbar-collapse collapse">
            <?php echo $this->elements->getMenu(); ?>
        </div>
    </div>
</nav>

<div class="container">
    <div class="row">
        <div class="col-sm-3">
            <div class="list-group">
                <a href="#" class="list-group-item active">
					Prepare Project
				</a>
                <?php
                    showProject($projectMaps, '1', $this);
                ?>
                <a href="#" class="list-group-item active">
					Project I
				</a>
                <?php
                    showProject($projectMaps, '2', $this);
                ?>
                <a href="#" class="list-group-item active">
	                Project II
                </a>
                <?php
                    showProject($projectMaps, '3', $this);
                ?>
            </div>
			<div class="list-group">
				<a href="#" class="list-group-item active">
					Menu
				</a>
				<a href="<?= $this->url->get(); ?>" class="list-group-item">
					Home
				</a>
				<a href="<?= $this->url->get('projects/proposed'); ?>" class="list-group-item">
					Proposed Project
				</a>
			</div>
        </div>
        <div class="col-sm-9">
            <?php echo $this->getContent(); ?>
        </div>
    </div>
</div>

<?php
function showProject($projectMaps, $level, $di)
{
    $current_semester = Semester::maximum(array("column" => "semester_id"));
	
	$found = false;
    foreach ($projectMaps as $projectMap)
    {
        $project = Project::findFirst("project_id='$projectMap->project_id' AND project_level_id='$level' AND project_status='Accept' AND semester_id='$current_semester'");
        if ($project)
        {
			 $projectMaps = ProjectMap::find("project_id='$project->project_id' AND map_type='owner'");

			 $str = "";
			 
			 for ($i = 0 ; $i < count($projectMaps) ; $i++)
			 {
				 if ($i != 0)
					$str += '<br>';
				$tuid = $projectMaps[$i]->user_id;
				$student = User::findFirst("id='$tuid'");
				$str .= $student->title.$student->name;
			 }
        ?>
            <a class="list-group-item" href="<?= $di->url->get('projects/manage/');?><?= $project->project_id?>" data-toggle="tooltip" data-placement="bottom" title="<?= $str; ?>"><?= $project->project_name ?></a>
        <?php
			$found = true;
        }
    }

	if (!$found)
	{
		?>
		<a class="list-group-item" href="#">ยังไม่ระบุ</a>
		<?php
	}
}
?>

<script>
	$('.list-group-item').tooltip();
</script>

