<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?= $this->url->get('index'); ?>">CoE-Project</a>
        </div>
        <div class="navbar-collapse collapse">
            <?php echo $this->elements->getMenu(); ?>
        </div>
    </div>
</nav>

<div class="container">
    <?php echo $this->getContent(); ?>
</div>
